blueprint:
  name: Rotate Through Scenes
  description: Cycle through a list of scenes each time the trigger entity activates.
  domain: automation
  input:
    trigger_entity:
      name: Trigger Entity
      description: Switch, button, or helper that triggers the next scene.
      selector:
        entity:
          domain: [switch, button, input_boolean]
    scenes:
      name: Scenes to Cycle
      description: List of scenes to rotate through.
      selector:
        entity:
          domain: scene
          multiple: true
    current_scene:
      name: Current Scene Helper
      description: Input select to store the currently active scene.
      selector:
        entity:
          domain: input_select

mode: single
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input trigger_entity

variables:
  scenes_list: !input scenes
  current_scene: !input current_scene

action:
  - choose:
      # If current helper value is not in scene list (e.g. after restart)
      - conditions:
          - condition: template
            value_template: "{{ states(current_scene) not in scenes_list }}"
        sequence:
          - service: scene.turn_on
            target:
              entity_id: "{{ scenes_list[0] }}"
          - service: input_select.select_option
            target:
              entity_id: "{{ current_scene }}"
            data:
              option: "{{ scenes_list[0] }}"
    default:
      - variables:
          index: "{{ (scenes_list.index(states(current_scene)) + 1) % scenes_list|length }}"
      - service: scene.turn_on
        target:
          entity_id: "{{ scenes_list[index] }}"
      - service: input_select.select_option
        target:
          entity_id: "{{ current_scene }}"
        data:
          option: "{{ scenes_list[index] }}"
